// Generated by CoffeeScript 1.3.3
(function() {
  var csspackage, fs, jspackage, path;

  jspackage = require('hem/lib/package');

  csspackage = require('hem/lib/css');

  fs = require('fs');

  path = require('path');

  module.exports = function(config) {
    var csspkg, jspkg, key, options, serveCSS, serveJavaScript, slugOptions, value;
    if (config == null) {
      config = {};
    }
    options = {
      jsPath: '/application.js',
      cssPath: '/application.css',
      cssFile: './css/index.styl',
      slug: './slug.json',
      libs: [],
      paths: ['./app'],
      dependencies: []
    };
    for (key in config) {
      value = config[key];
      options[key] = value;
    }
    if (options.slug && path.existsSync(options.slug)) {
      slugOptions = JSON.parse(fs.readFileSync(options.slug));
      for (key in slugOptions) {
        value = slugOptions[key];
        options[key] = value;
      }
    }
    jspkg = jspackage.createPackage(options);
    serveJavaScript = function(req, res, next) {
      var js;
      js = jspkg.compile();
      res.writeHead(200, {
        'Content-Type': 'text/javascript',
        'Content-Length': js.length
      });
      return res.end(js);
    };
    csspkg = csspackage.createPackage(options.cssFile);
    serveCSS = function(req, res, next) {
      var css;
      css = csspkg.compile();
      res.writeHead(200, {
        'Content-Type': 'text/css',
        'Content-Length': css.length
      });
      return res.end(css);
    };
    return function(req, res, next) {
      if (req.method === 'GET' && req.path === options.jsPath) {
        return serveJavaScript(req, res, next);
      }
      if (req.method === 'GET' && req.path === options.cssPath) {
        return serveCSS(req, res, next);
      }
      return next();
    };
  };

}).call(this);
